base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- dockerfile_path: .ci/Dockerfile
  to: registry
releases:
  arm64-initial:
    integration:
      name: "4.14"
      namespace: ocp
      architecture: arm64
  arm64-latest:
    integration:
      include_built_images: true
      name: "4.14"
      namespace: ocp
      architecture: arm64
  initial:
    integration:
      name: "4.14"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.14"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: registry-test
  steps:
    cluster_profile: aws-devfile
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
    env:
      BASE_DOMAIN: devfile-ci.com
      OCP_ARCH: arm64
    test:
    - as: registry-test-steps
      commands: |
        export PATH=$PATH:/tmp/bin
        mkdir /tmp/bin
        curl -L --fail https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/candidate-4.14/openshift-client-linux.tar.gz | tar xvzf - -C /tmp/bin/ oc
        chmod ug+x /tmp/bin/oc
        .ci/openshift_integration.sh arm64
      dependencies:
      - env: REGISTRY_IMAGE
        name: registry
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ipi-aws
zz_generated_metadata:
  branch: main
  org: devfile
  repo: registry
  variant: v4.14
